# Generated by Django 4.1 on 2022-12-30 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("all_info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Free",
            fields=[
                ("free_id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("comment", models.CharField(max_length=200)),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.group",
                    ),
                ),
                (
                    "info",
                    models.ForeignKey(
                        db_column="info_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("gallery_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(max_length=200)),
                ("picture", models.CharField(max_length=200)),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.group",
                    ),
                ),
                (
                    "info",
                    models.ForeignKey(
                        db_column="info_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Join",
            fields=[
                ("join_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(max_length=200)),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.group",
                    ),
                ),
                (
                    "info",
                    models.ForeignKey(
                        db_column="info_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Good",
            fields=[
                ("good_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "free",
                    models.ForeignKey(
                        db_column="free_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="write.free",
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        db_column="gallery_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="write.gallery",
                    ),
                ),
                (
                    "info",
                    models.ForeignKey(
                        db_column="info_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="all_info.info",
                    ),
                ),
                (
                    "join",
                    models.ForeignKey(
                        db_column="join_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="write.join",
                    ),
                ),
            ],
        ),
    ]
