# Generated by Django 4.1 on 2023-01-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("write", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="free",
            name="comment",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="free",
            name="text",
            field=models.TextField(null=True, verbose_name="글 내용"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="comment",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="picture",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="join",
            name="comment",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="join",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
