# Generated by Django 4.1 on 2023-01-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("select_moim", "0001_initial"),
        ("write", "0002_alter_free_comment_alter_free_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="free",
            name="select_moim",
            field=models.ForeignKey(
                db_column="select_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="select_moim.select_moim",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="select_moim",
            field=models.ForeignKey(
                db_column="select_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="select_moim.select_moim",
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="select_moim",
            field=models.ForeignKey(
                db_column="select_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="select_moim.select_moim",
            ),
        ),
        migrations.AddField(
            model_name="join",
            name="select_moim",
            field=models.ForeignKey(
                db_column="select_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="select_moim.select_moim",
            ),
        ),
    ]
